global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'formation_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['formation-service:8080']
        labels:
          application: 'formation Service Application'
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']
        labels:
          application: 'User Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'
